server:
  port: 9999
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/energysync
    username: postgres
    password: 12345
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:

      ddl-auto: none
    open-in-view: false
  data:
    mongodb:
      port: '27017'
      host: localhost
      database: wlc
multitenancy:
  public:
    liquibase:
      changeLog: classpath:db/changelog/master/db.changelog-master.xml
  tenant:
    liquibase:
      changeLog: classpath:db/changelog/company/db.changelog-company.xml

mail:
  username: healthbizzas@gmail.com
  password: vnfhgnkddbbrosni
  host: smtp.gmail.com
  port: 587
